// -------------------------------------------------------------
//
// Module: Stage2_HB1
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-12-07 02:26:00
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// CoeffMultipliers: CSD
// TargetDirectory: hdl_src_tiny
// Name: Stage2_HB1
// InputDataType: numerictype(1,22,18)
// TargetLanguage: Verilog
// TestBenchUserStimulus:  User data, length 10
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure   : Direct-Form FIR Polyphase Decimator
// Decimation Factor  : 2
// Polyphase Length   : 6
// Filter Length      : 11
// Stable             : Yes
// Linear Phase       : Yes (Type 1)
//
// Arithmetic         : fixed
// Numerator          : s16,15 -> [-1 1)
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module Stage2_HB1
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [21:0] filter_in; //sfix22_En18
  output  signed [21:0] filter_out; //sfix22_En18
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: Stage2_HB1
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b0000100110101010; //sfix16_En15
  parameter signed [15:0] coeffphase1_2 = 16'b1111001110001000; //sfix16_En15
  parameter signed [15:0] coeffphase1_3 = 16'b0010100001011011; //sfix16_En15
  parameter signed [15:0] coeffphase1_4 = 16'b0010100001011011; //sfix16_En15
  parameter signed [15:0] coeffphase1_5 = 16'b1111001110001000; //sfix16_En15
  parameter signed [15:0] coeffphase1_6 = 16'b0000100110101010; //sfix16_En15
  parameter signed [15:0] coeffphase2_1 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase2_2 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase2_3 = 16'b0100000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase2_4 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase2_5 = 16'b0000000000000000; //sfix16_En15
  parameter signed [15:0] coeffphase2_6 = 16'b0000000000000000; //sfix16_En15

  // Signals
  reg  [1:0] ring_count; // ufix2
  wire phase_0; // boolean
  wire phase_1; // boolean
  reg  ce_out_reg; // boolean
  reg  signed [21:0] input_register; // sfix22_En18
  reg  signed [21:0] input_pipeline_phase0 [0:4] ; // sfix22_En18
  reg  signed [21:0] input_pipeline_phase1 [0:2] ; // sfix22_En18
  wire signed [37:0] product_phase0_1; // sfix38_En33
  wire signed [33:0] mulcsd_temp; // sfix34_En33
  wire signed [37:0] product_phase0_2; // sfix38_En33
  wire signed [34:0] mulcsd_temp_1; // sfix35_En33
  wire signed [37:0] product_phase0_3; // sfix38_En33
  wire signed [35:0] mulcsd_temp_2; // sfix36_En33
  wire signed [37:0] product_phase0_4; // sfix38_En33
  wire signed [35:0] mulcsd_temp_3; // sfix36_En33
  wire signed [37:0] product_phase0_5; // sfix38_En33
  wire signed [34:0] mulcsd_temp_4; // sfix35_En33
  wire signed [37:0] product_phase0_6; // sfix38_En33
  wire signed [33:0] mulcsd_temp_5; // sfix34_En33
  wire signed [37:0] product_phase1_3; // sfix38_En33
  wire signed [53:0] quantized_sum; // sfix54_En33
  wire signed [53:0] sum1; // sfix54_En33
  wire signed [53:0] add_signext; // sfix54_En33
  wire signed [53:0] add_signext_1; // sfix54_En33
  wire signed [54:0] add_temp; // sfix55_En33
  wire signed [53:0] sum2; // sfix54_En33
  wire signed [53:0] add_signext_2; // sfix54_En33
  wire signed [53:0] add_signext_3; // sfix54_En33
  wire signed [54:0] add_temp_1; // sfix55_En33
  wire signed [53:0] sum3; // sfix54_En33
  wire signed [53:0] add_signext_4; // sfix54_En33
  wire signed [53:0] add_signext_5; // sfix54_En33
  wire signed [54:0] add_temp_2; // sfix55_En33
  wire signed [53:0] sum4; // sfix54_En33
  wire signed [53:0] add_signext_6; // sfix54_En33
  wire signed [53:0] add_signext_7; // sfix54_En33
  wire signed [54:0] add_temp_3; // sfix55_En33
  wire signed [53:0] sum5; // sfix54_En33
  wire signed [53:0] add_signext_8; // sfix54_En33
  wire signed [53:0] add_signext_9; // sfix54_En33
  wire signed [54:0] add_temp_4; // sfix55_En33
  wire signed [53:0] sum6; // sfix54_En33
  wire signed [53:0] add_signext_10; // sfix54_En33
  wire signed [53:0] add_signext_11; // sfix54_En33
  wire signed [54:0] add_temp_5; // sfix55_En33
  wire signed [21:0] output_typeconvert; // sfix22_En18
  reg  signed [21:0] output_register; // sfix22_En18

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        ring_count <= 1;
      end
      else begin
                if (clk_enable == 1'b1) begin
        ring_count <= {ring_count[0], ring_count[1]};
              end
            end
    end // ce_output

  assign  phase_0 = ring_count[0]  && clk_enable;

  assign  phase_1 = ring_count[1]  && clk_enable;

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_1;
      end
    end // ce_output_register

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase0_process
      if (reset == 1'b1) begin
        input_pipeline_phase0[0] <= 0;
        input_pipeline_phase0[1] <= 0;
        input_pipeline_phase0[2] <= 0;
        input_pipeline_phase0[3] <= 0;
        input_pipeline_phase0[4] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          input_pipeline_phase0[0] <= input_register;
          input_pipeline_phase0[1] <= input_pipeline_phase0[0];
          input_pipeline_phase0[2] <= input_pipeline_phase0[1];
          input_pipeline_phase0[3] <= input_pipeline_phase0[2];
          input_pipeline_phase0[4] <= input_pipeline_phase0[3];
        end
      end
    end // Delay_Pipeline_Phase0_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase1_process
      if (reset == 1'b1) begin
        input_pipeline_phase1[0] <= 0;
        input_pipeline_phase1[1] <= 0;
        input_pipeline_phase1[2] <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          input_pipeline_phase1[0] <= input_register;
          input_pipeline_phase1[1] <= input_pipeline_phase1[0];
          input_pipeline_phase1[2] <= input_pipeline_phase1[1];
        end
      end
    end // Delay_Pipeline_Phase1_process


  assign mulcsd_temp = 
        $signed({input_register, 11'b00000000000}) +
        $signed({input_register, 9'b000000000}) -
        $signed({input_register, 7'b0000000}) +
        $signed({input_register, 5'b00000}) +
        $signed({input_register, 3'b000}) +
        $signed({input_register, 1'b0});
  assign product_phase0_1 = $signed({{4{mulcsd_temp[33]}}, mulcsd_temp});

  assign mulcsd_temp_1 = - (
        $signed({input_pipeline_phase0[0], 12'b000000000000}) -
        $signed({input_pipeline_phase0[0], 10'b0000000000}) +
        $signed({input_pipeline_phase0[0], 7'b0000000}) -
        $signed({input_pipeline_phase0[0], 3'b000}));
  assign product_phase0_2 = $signed({{3{mulcsd_temp_1[34]}}, mulcsd_temp_1});

  assign mulcsd_temp_2 = 
        $signed({input_pipeline_phase0[1], 13'b0000000000000}) +
        $signed({input_pipeline_phase0[1], 11'b00000000000}) +
        $signed({input_pipeline_phase0[1], 6'b000000}) +
        $signed({input_pipeline_phase0[1], 5'b00000}) -
        $signed({input_pipeline_phase0[1], 3'b000}) +
        $signed({input_pipeline_phase0[1], 2'b00}) -
        input_pipeline_phase0[1];
  assign product_phase0_3 = $signed({{2{mulcsd_temp_2[35]}}, mulcsd_temp_2});

  assign mulcsd_temp_3 = 
        $signed({input_pipeline_phase0[2], 13'b0000000000000}) +
        $signed({input_pipeline_phase0[2], 11'b00000000000}) +
        $signed({input_pipeline_phase0[2], 6'b000000}) +
        $signed({input_pipeline_phase0[2], 5'b00000}) -
        $signed({input_pipeline_phase0[2], 3'b000}) +
        $signed({input_pipeline_phase0[2], 2'b00}) -
        input_pipeline_phase0[2];
  assign product_phase0_4 = $signed({{2{mulcsd_temp_3[35]}}, mulcsd_temp_3});

  assign mulcsd_temp_4 = - (
        $signed({input_pipeline_phase0[3], 12'b000000000000}) -
        $signed({input_pipeline_phase0[3], 10'b0000000000}) +
        $signed({input_pipeline_phase0[3], 7'b0000000}) -
        $signed({input_pipeline_phase0[3], 3'b000}));
  assign product_phase0_5 = $signed({{3{mulcsd_temp_4[34]}}, mulcsd_temp_4});

  assign mulcsd_temp_5 = 
        $signed({input_pipeline_phase0[4], 11'b00000000000}) +
        $signed({input_pipeline_phase0[4], 9'b000000000}) -
        $signed({input_pipeline_phase0[4], 7'b0000000}) +
        $signed({input_pipeline_phase0[4], 5'b00000}) +
        $signed({input_pipeline_phase0[4], 3'b000}) +
        $signed({input_pipeline_phase0[4], 1'b0});
  assign product_phase0_6 = $signed({{4{mulcsd_temp_5[33]}}, mulcsd_temp_5});

  assign product_phase1_3 = $signed({input_pipeline_phase1[2][21:0], 14'b00000000000000});

  assign quantized_sum = $signed({{16{product_phase1_3[37]}}, product_phase1_3});

  assign add_signext = quantized_sum;
  assign add_signext_1 = $signed({{16{product_phase0_1[37]}}, product_phase0_1});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[53:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{16{product_phase0_2[37]}}, product_phase0_2});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[53:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{16{product_phase0_3[37]}}, product_phase0_3});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[53:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{16{product_phase0_4[37]}}, product_phase0_4});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[53:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{16{product_phase0_5[37]}}, product_phase0_5});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[53:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{16{product_phase0_6[37]}}, product_phase0_6});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[53:0];

  assign output_typeconvert = sum6[36:15];

  always @ (posedge clk or posedge reset)
    begin: output_register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // output_register_process

  // Assignment Statements
  assign ce_out = ce_out_reg;
  assign filter_out = output_register;
endmodule  // Stage2_HB1
