// -------------------------------------------------------------
//
// Module: Stage5_FIR
// Generated by MATLAB(R) 24.1 and Filter Design HDL Coder 24.1.
// Generated on: 2025-12-07 02:26:05
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// CoeffMultipliers: CSD
// TargetDirectory: hdl_src_tiny
// Name: Stage5_FIR
// InputDataType: numerictype(1,22,18)
// TargetLanguage: Verilog
// TestBenchUserStimulus:  User data, length 10
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure   : Direct-Form FIR Polyphase Decimator
// Decimation Factor  : 2
// Polyphase Length   : 17
// Filter Length      : 33
// Stable             : Yes
// Linear Phase       : Yes (Type 1)
//
// Arithmetic         : fixed
// Numerator          : s16,15 -> [-1 1)
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module Stage5_FIR
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [21:0] filter_in; //sfix22_En18
  output  signed [21:0] filter_out; //sfix22_En18
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: Stage5_FIR
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b1111111111111011; //sfix16_En15
  parameter signed [15:0] coeffphase1_2 = 16'b0000000000100000; //sfix16_En15
  parameter signed [15:0] coeffphase1_3 = 16'b1111111110110000; //sfix16_En15
  parameter signed [15:0] coeffphase1_4 = 16'b0000000010100000; //sfix16_En15
  parameter signed [15:0] coeffphase1_5 = 16'b1111111011110110; //sfix16_En15
  parameter signed [15:0] coeffphase1_6 = 16'b0000000110000011; //sfix16_En15
  parameter signed [15:0] coeffphase1_7 = 16'b1111111000001101; //sfix16_En15
  parameter signed [15:0] coeffphase1_8 = 16'b0000001001000011; //sfix16_En15
  parameter signed [15:0] coeffphase1_9 = 16'b0011110110100000; //sfix16_En15
  parameter signed [15:0] coeffphase1_10 = 16'b0000001001000011; //sfix16_En15
  parameter signed [15:0] coeffphase1_11 = 16'b1111111000001101; //sfix16_En15
  parameter signed [15:0] coeffphase1_12 = 16'b0000000110000011; //sfix16_En15
  parameter signed [15:0] coeffphase1_13 = 16'b1111111011110110; //sfix16_En15
  parameter signed [15:0] coeffphase1_14 = 16'b0000000010100000; //sfix16_En15
  parameter signed [15:0] coeffphase1_15 = 16'b1111111110110000; //sfix16_En15
  parameter signed [15:0] coeffphase1_16 = 16'b0000000000100000; //sfix16_En15
  parameter signed [15:0] coeffphase1_17 = 16'b1111111111111011; //sfix16_En15
  parameter signed [15:0] coeffphase2_1 = 16'b1111111111111110; //sfix16_En15
  parameter signed [15:0] coeffphase2_2 = 16'b0000000000100100; //sfix16_En15
  parameter signed [15:0] coeffphase2_3 = 16'b1111111110000100; //sfix16_En15
  parameter signed [15:0] coeffphase2_4 = 16'b0000000101000001; //sfix16_En15
  parameter signed [15:0] coeffphase2_5 = 16'b1111110100111100; //sfix16_En15
  parameter signed [15:0] coeffphase2_6 = 16'b0000010110100001; //sfix16_En15
  parameter signed [15:0] coeffphase2_7 = 16'b1111010000010101; //sfix16_En15
  parameter signed [15:0] coeffphase2_8 = 16'b0010100000101001; //sfix16_En15
  parameter signed [15:0] coeffphase2_9 = 16'b0010100000101001; //sfix16_En15
  parameter signed [15:0] coeffphase2_10 = 16'b1111010000010101; //sfix16_En15
  parameter signed [15:0] coeffphase2_11 = 16'b0000010110100001; //sfix16_En15
  parameter signed [15:0] coeffphase2_12 = 16'b1111110100111100; //sfix16_En15
  parameter signed [15:0] coeffphase2_13 = 16'b0000000101000001; //sfix16_En15
  parameter signed [15:0] coeffphase2_14 = 16'b1111111110000100; //sfix16_En15
  parameter signed [15:0] coeffphase2_15 = 16'b0000000000100100; //sfix16_En15
  parameter signed [15:0] coeffphase2_16 = 16'b1111111111111110; //sfix16_En15
  parameter signed [15:0] coeffphase2_17 = 16'b0000000000000000; //sfix16_En15

  // Signals
  reg  [1:0] ring_count; // ufix2
  wire phase_0; // boolean
  wire phase_1; // boolean
  reg  ce_out_reg; // boolean
  reg  signed [21:0] input_register; // sfix22_En18
  reg  signed [21:0] input_pipeline_phase0 [0:15] ; // sfix22_En18
  reg  signed [21:0] input_pipeline_phase1 [0:15] ; // sfix22_En18
  wire signed [37:0] product_phase0_1; // sfix38_En33
  wire signed [24:0] mulcsd_temp; // sfix25_En33
  wire signed [37:0] product_phase0_2; // sfix38_En33
  wire signed [37:0] product_phase0_3; // sfix38_En33
  wire signed [28:0] mulcsd_temp_1; // sfix29_En33
  wire signed [37:0] product_phase0_4; // sfix38_En33
  wire signed [29:0] mulcsd_temp_2; // sfix30_En33
  wire signed [37:0] product_phase0_5; // sfix38_En33
  wire signed [30:0] mulcsd_temp_3; // sfix31_En33
  wire signed [37:0] product_phase0_6; // sfix38_En33
  wire signed [31:0] mulcsd_temp_4; // sfix32_En33
  wire signed [37:0] product_phase0_7; // sfix38_En33
  wire signed [31:0] mulcsd_temp_5; // sfix32_En33
  wire signed [37:0] product_phase0_8; // sfix38_En33
  wire signed [31:0] mulcsd_temp_6; // sfix32_En33
  wire signed [37:0] product_phase0_9; // sfix38_En33
  wire signed [36:0] mulcsd_temp_7; // sfix37_En33
  wire signed [37:0] product_phase0_10; // sfix38_En33
  wire signed [31:0] mulcsd_temp_8; // sfix32_En33
  wire signed [37:0] product_phase0_11; // sfix38_En33
  wire signed [31:0] mulcsd_temp_9; // sfix32_En33
  wire signed [37:0] product_phase0_12; // sfix38_En33
  wire signed [31:0] mulcsd_temp_10; // sfix32_En33
  wire signed [37:0] product_phase0_13; // sfix38_En33
  wire signed [30:0] mulcsd_temp_11; // sfix31_En33
  wire signed [37:0] product_phase0_14; // sfix38_En33
  wire signed [29:0] mulcsd_temp_12; // sfix30_En33
  wire signed [37:0] product_phase0_15; // sfix38_En33
  wire signed [28:0] mulcsd_temp_13; // sfix29_En33
  wire signed [37:0] product_phase0_16; // sfix38_En33
  wire signed [37:0] product_phase0_17; // sfix38_En33
  wire signed [24:0] mulcsd_temp_14; // sfix25_En33
  wire signed [37:0] product_phase1_1; // sfix38_En33
  wire signed [22:0] mulpwr2_temp; // sfix23_En18
  wire signed [37:0] product_phase1_2; // sfix38_En33
  wire signed [27:0] mulcsd_temp_15; // sfix28_En33
  wire signed [37:0] product_phase1_3; // sfix38_En33
  wire signed [29:0] mulcsd_temp_16; // sfix30_En33
  wire signed [37:0] product_phase1_4; // sfix38_En33
  wire signed [30:0] mulcsd_temp_17; // sfix31_En33
  wire signed [37:0] product_phase1_5; // sfix38_En33
  wire signed [31:0] mulcsd_temp_18; // sfix32_En33
  wire signed [37:0] product_phase1_6; // sfix38_En33
  wire signed [32:0] mulcsd_temp_19; // sfix33_En33
  wire signed [37:0] product_phase1_7; // sfix38_En33
  wire signed [33:0] mulcsd_temp_20; // sfix34_En33
  wire signed [37:0] product_phase1_8; // sfix38_En33
  wire signed [35:0] mulcsd_temp_21; // sfix36_En33
  wire signed [37:0] product_phase1_9; // sfix38_En33
  wire signed [35:0] mulcsd_temp_22; // sfix36_En33
  wire signed [37:0] product_phase1_10; // sfix38_En33
  wire signed [33:0] mulcsd_temp_23; // sfix34_En33
  wire signed [37:0] product_phase1_11; // sfix38_En33
  wire signed [32:0] mulcsd_temp_24; // sfix33_En33
  wire signed [37:0] product_phase1_12; // sfix38_En33
  wire signed [31:0] mulcsd_temp_25; // sfix32_En33
  wire signed [37:0] product_phase1_13; // sfix38_En33
  wire signed [30:0] mulcsd_temp_26; // sfix31_En33
  wire signed [37:0] product_phase1_14; // sfix38_En33
  wire signed [29:0] mulcsd_temp_27; // sfix30_En33
  wire signed [37:0] product_phase1_15; // sfix38_En33
  wire signed [27:0] mulcsd_temp_28; // sfix28_En33
  wire signed [37:0] product_phase1_16; // sfix38_En33
  wire signed [22:0] mulpwr2_temp_1; // sfix23_En18
  wire signed [53:0] quantized_sum; // sfix54_En33
  wire signed [53:0] sum1; // sfix54_En33
  wire signed [53:0] add_signext; // sfix54_En33
  wire signed [53:0] add_signext_1; // sfix54_En33
  wire signed [54:0] add_temp; // sfix55_En33
  wire signed [53:0] sum2; // sfix54_En33
  wire signed [53:0] add_signext_2; // sfix54_En33
  wire signed [53:0] add_signext_3; // sfix54_En33
  wire signed [54:0] add_temp_1; // sfix55_En33
  wire signed [53:0] sum3; // sfix54_En33
  wire signed [53:0] add_signext_4; // sfix54_En33
  wire signed [53:0] add_signext_5; // sfix54_En33
  wire signed [54:0] add_temp_2; // sfix55_En33
  wire signed [53:0] sum4; // sfix54_En33
  wire signed [53:0] add_signext_6; // sfix54_En33
  wire signed [53:0] add_signext_7; // sfix54_En33
  wire signed [54:0] add_temp_3; // sfix55_En33
  wire signed [53:0] sum5; // sfix54_En33
  wire signed [53:0] add_signext_8; // sfix54_En33
  wire signed [53:0] add_signext_9; // sfix54_En33
  wire signed [54:0] add_temp_4; // sfix55_En33
  wire signed [53:0] sum6; // sfix54_En33
  wire signed [53:0] add_signext_10; // sfix54_En33
  wire signed [53:0] add_signext_11; // sfix54_En33
  wire signed [54:0] add_temp_5; // sfix55_En33
  wire signed [53:0] sum7; // sfix54_En33
  wire signed [53:0] add_signext_12; // sfix54_En33
  wire signed [53:0] add_signext_13; // sfix54_En33
  wire signed [54:0] add_temp_6; // sfix55_En33
  wire signed [53:0] sum8; // sfix54_En33
  wire signed [53:0] add_signext_14; // sfix54_En33
  wire signed [53:0] add_signext_15; // sfix54_En33
  wire signed [54:0] add_temp_7; // sfix55_En33
  wire signed [53:0] sum9; // sfix54_En33
  wire signed [53:0] add_signext_16; // sfix54_En33
  wire signed [53:0] add_signext_17; // sfix54_En33
  wire signed [54:0] add_temp_8; // sfix55_En33
  wire signed [53:0] sum10; // sfix54_En33
  wire signed [53:0] add_signext_18; // sfix54_En33
  wire signed [53:0] add_signext_19; // sfix54_En33
  wire signed [54:0] add_temp_9; // sfix55_En33
  wire signed [53:0] sum11; // sfix54_En33
  wire signed [53:0] add_signext_20; // sfix54_En33
  wire signed [53:0] add_signext_21; // sfix54_En33
  wire signed [54:0] add_temp_10; // sfix55_En33
  wire signed [53:0] sum12; // sfix54_En33
  wire signed [53:0] add_signext_22; // sfix54_En33
  wire signed [53:0] add_signext_23; // sfix54_En33
  wire signed [54:0] add_temp_11; // sfix55_En33
  wire signed [53:0] sum13; // sfix54_En33
  wire signed [53:0] add_signext_24; // sfix54_En33
  wire signed [53:0] add_signext_25; // sfix54_En33
  wire signed [54:0] add_temp_12; // sfix55_En33
  wire signed [53:0] sum14; // sfix54_En33
  wire signed [53:0] add_signext_26; // sfix54_En33
  wire signed [53:0] add_signext_27; // sfix54_En33
  wire signed [54:0] add_temp_13; // sfix55_En33
  wire signed [53:0] sum15; // sfix54_En33
  wire signed [53:0] add_signext_28; // sfix54_En33
  wire signed [53:0] add_signext_29; // sfix54_En33
  wire signed [54:0] add_temp_14; // sfix55_En33
  wire signed [53:0] sum16; // sfix54_En33
  wire signed [53:0] add_signext_30; // sfix54_En33
  wire signed [53:0] add_signext_31; // sfix54_En33
  wire signed [54:0] add_temp_15; // sfix55_En33
  wire signed [53:0] sum17; // sfix54_En33
  wire signed [53:0] add_signext_32; // sfix54_En33
  wire signed [53:0] add_signext_33; // sfix54_En33
  wire signed [54:0] add_temp_16; // sfix55_En33
  wire signed [53:0] sum18; // sfix54_En33
  wire signed [53:0] add_signext_34; // sfix54_En33
  wire signed [53:0] add_signext_35; // sfix54_En33
  wire signed [54:0] add_temp_17; // sfix55_En33
  wire signed [53:0] sum19; // sfix54_En33
  wire signed [53:0] add_signext_36; // sfix54_En33
  wire signed [53:0] add_signext_37; // sfix54_En33
  wire signed [54:0] add_temp_18; // sfix55_En33
  wire signed [53:0] sum20; // sfix54_En33
  wire signed [53:0] add_signext_38; // sfix54_En33
  wire signed [53:0] add_signext_39; // sfix54_En33
  wire signed [54:0] add_temp_19; // sfix55_En33
  wire signed [53:0] sum21; // sfix54_En33
  wire signed [53:0] add_signext_40; // sfix54_En33
  wire signed [53:0] add_signext_41; // sfix54_En33
  wire signed [54:0] add_temp_20; // sfix55_En33
  wire signed [53:0] sum22; // sfix54_En33
  wire signed [53:0] add_signext_42; // sfix54_En33
  wire signed [53:0] add_signext_43; // sfix54_En33
  wire signed [54:0] add_temp_21; // sfix55_En33
  wire signed [53:0] sum23; // sfix54_En33
  wire signed [53:0] add_signext_44; // sfix54_En33
  wire signed [53:0] add_signext_45; // sfix54_En33
  wire signed [54:0] add_temp_22; // sfix55_En33
  wire signed [53:0] sum24; // sfix54_En33
  wire signed [53:0] add_signext_46; // sfix54_En33
  wire signed [53:0] add_signext_47; // sfix54_En33
  wire signed [54:0] add_temp_23; // sfix55_En33
  wire signed [53:0] sum25; // sfix54_En33
  wire signed [53:0] add_signext_48; // sfix54_En33
  wire signed [53:0] add_signext_49; // sfix54_En33
  wire signed [54:0] add_temp_24; // sfix55_En33
  wire signed [53:0] sum26; // sfix54_En33
  wire signed [53:0] add_signext_50; // sfix54_En33
  wire signed [53:0] add_signext_51; // sfix54_En33
  wire signed [54:0] add_temp_25; // sfix55_En33
  wire signed [53:0] sum27; // sfix54_En33
  wire signed [53:0] add_signext_52; // sfix54_En33
  wire signed [53:0] add_signext_53; // sfix54_En33
  wire signed [54:0] add_temp_26; // sfix55_En33
  wire signed [53:0] sum28; // sfix54_En33
  wire signed [53:0] add_signext_54; // sfix54_En33
  wire signed [53:0] add_signext_55; // sfix54_En33
  wire signed [54:0] add_temp_27; // sfix55_En33
  wire signed [53:0] sum29; // sfix54_En33
  wire signed [53:0] add_signext_56; // sfix54_En33
  wire signed [53:0] add_signext_57; // sfix54_En33
  wire signed [54:0] add_temp_28; // sfix55_En33
  wire signed [53:0] sum30; // sfix54_En33
  wire signed [53:0] add_signext_58; // sfix54_En33
  wire signed [53:0] add_signext_59; // sfix54_En33
  wire signed [54:0] add_temp_29; // sfix55_En33
  wire signed [53:0] sum31; // sfix54_En33
  wire signed [53:0] add_signext_60; // sfix54_En33
  wire signed [53:0] add_signext_61; // sfix54_En33
  wire signed [54:0] add_temp_30; // sfix55_En33
  wire signed [53:0] sum32; // sfix54_En33
  wire signed [53:0] add_signext_62; // sfix54_En33
  wire signed [53:0] add_signext_63; // sfix54_En33
  wire signed [54:0] add_temp_31; // sfix55_En33
  wire signed [21:0] output_typeconvert; // sfix22_En18
  reg  signed [21:0] output_register; // sfix22_En18

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        ring_count <= 1;
      end
      else begin
                if (clk_enable == 1'b1) begin
        ring_count <= {ring_count[0], ring_count[1]};
              end
            end
    end // ce_output

  assign  phase_0 = ring_count[0]  && clk_enable;

  assign  phase_1 = ring_count[1]  && clk_enable;

  //   ------------------ CE Output Register ------------------

  always @ (posedge clk or posedge reset)
    begin: ce_output_register
      if (reset == 1'b1) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= phase_1;
      end
    end // ce_output_register

  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase0_process
      if (reset == 1'b1) begin
        input_pipeline_phase0[0] <= 0;
        input_pipeline_phase0[1] <= 0;
        input_pipeline_phase0[2] <= 0;
        input_pipeline_phase0[3] <= 0;
        input_pipeline_phase0[4] <= 0;
        input_pipeline_phase0[5] <= 0;
        input_pipeline_phase0[6] <= 0;
        input_pipeline_phase0[7] <= 0;
        input_pipeline_phase0[8] <= 0;
        input_pipeline_phase0[9] <= 0;
        input_pipeline_phase0[10] <= 0;
        input_pipeline_phase0[11] <= 0;
        input_pipeline_phase0[12] <= 0;
        input_pipeline_phase0[13] <= 0;
        input_pipeline_phase0[14] <= 0;
        input_pipeline_phase0[15] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          input_pipeline_phase0[0] <= input_register;
          input_pipeline_phase0[1] <= input_pipeline_phase0[0];
          input_pipeline_phase0[2] <= input_pipeline_phase0[1];
          input_pipeline_phase0[3] <= input_pipeline_phase0[2];
          input_pipeline_phase0[4] <= input_pipeline_phase0[3];
          input_pipeline_phase0[5] <= input_pipeline_phase0[4];
          input_pipeline_phase0[6] <= input_pipeline_phase0[5];
          input_pipeline_phase0[7] <= input_pipeline_phase0[6];
          input_pipeline_phase0[8] <= input_pipeline_phase0[7];
          input_pipeline_phase0[9] <= input_pipeline_phase0[8];
          input_pipeline_phase0[10] <= input_pipeline_phase0[9];
          input_pipeline_phase0[11] <= input_pipeline_phase0[10];
          input_pipeline_phase0[12] <= input_pipeline_phase0[11];
          input_pipeline_phase0[13] <= input_pipeline_phase0[12];
          input_pipeline_phase0[14] <= input_pipeline_phase0[13];
          input_pipeline_phase0[15] <= input_pipeline_phase0[14];
        end
      end
    end // Delay_Pipeline_Phase0_process


  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_Phase1_process
      if (reset == 1'b1) begin
        input_pipeline_phase1[0] <= 0;
        input_pipeline_phase1[1] <= 0;
        input_pipeline_phase1[2] <= 0;
        input_pipeline_phase1[3] <= 0;
        input_pipeline_phase1[4] <= 0;
        input_pipeline_phase1[5] <= 0;
        input_pipeline_phase1[6] <= 0;
        input_pipeline_phase1[7] <= 0;
        input_pipeline_phase1[8] <= 0;
        input_pipeline_phase1[9] <= 0;
        input_pipeline_phase1[10] <= 0;
        input_pipeline_phase1[11] <= 0;
        input_pipeline_phase1[12] <= 0;
        input_pipeline_phase1[13] <= 0;
        input_pipeline_phase1[14] <= 0;
        input_pipeline_phase1[15] <= 0;
      end
      else begin
        if (phase_0 == 1'b1) begin
          input_pipeline_phase1[0] <= input_register;
          input_pipeline_phase1[1] <= input_pipeline_phase1[0];
          input_pipeline_phase1[2] <= input_pipeline_phase1[1];
          input_pipeline_phase1[3] <= input_pipeline_phase1[2];
          input_pipeline_phase1[4] <= input_pipeline_phase1[3];
          input_pipeline_phase1[5] <= input_pipeline_phase1[4];
          input_pipeline_phase1[6] <= input_pipeline_phase1[5];
          input_pipeline_phase1[7] <= input_pipeline_phase1[6];
          input_pipeline_phase1[8] <= input_pipeline_phase1[7];
          input_pipeline_phase1[9] <= input_pipeline_phase1[8];
          input_pipeline_phase1[10] <= input_pipeline_phase1[9];
          input_pipeline_phase1[11] <= input_pipeline_phase1[10];
          input_pipeline_phase1[12] <= input_pipeline_phase1[11];
          input_pipeline_phase1[13] <= input_pipeline_phase1[12];
          input_pipeline_phase1[14] <= input_pipeline_phase1[13];
          input_pipeline_phase1[15] <= input_pipeline_phase1[14];
        end
      end
    end // Delay_Pipeline_Phase1_process


  assign mulcsd_temp = - (
        $signed({input_register, 2'b00}) +
        input_register);
  assign product_phase0_1 = $signed({{13{mulcsd_temp[24]}}, mulcsd_temp});

  assign product_phase0_2 = $signed({input_pipeline_phase0[0][21:0], 5'b00000});

  assign mulcsd_temp_1 = - (
        $signed({input_pipeline_phase0[1], 6'b000000}) +
        $signed({input_pipeline_phase0[1], 4'b0000}));
  assign product_phase0_3 = $signed({{9{mulcsd_temp_1[28]}}, mulcsd_temp_1});

  assign mulcsd_temp_2 = 
        $signed({input_pipeline_phase0[2], 7'b0000000}) +
        $signed({input_pipeline_phase0[2], 5'b00000});
  assign product_phase0_4 = $signed({{8{mulcsd_temp_2[29]}}, mulcsd_temp_2});

  assign mulcsd_temp_3 = - (
        $signed({input_pipeline_phase0[3], 8'b00000000}) +
        $signed({input_pipeline_phase0[3], 3'b000}) +
        $signed({input_pipeline_phase0[3], 1'b0}));
  assign product_phase0_5 = $signed({{7{mulcsd_temp_3[30]}}, mulcsd_temp_3});

  assign mulcsd_temp_4 = 
        $signed({input_pipeline_phase0[4], 9'b000000000}) -
        $signed({input_pipeline_phase0[4], 7'b0000000}) +
        $signed({input_pipeline_phase0[4], 2'b00}) -
        input_pipeline_phase0[4];
  assign product_phase0_6 = $signed({{6{mulcsd_temp_4[31]}}, mulcsd_temp_4});

  assign mulcsd_temp_5 = - (
        $signed({input_pipeline_phase0[5], 9'b000000000}) -
        $signed({input_pipeline_phase0[5], 4'b0000}) +
        $signed({input_pipeline_phase0[5], 2'b00}) -
        input_pipeline_phase0[5]);
  assign product_phase0_7 = $signed({{6{mulcsd_temp_5[31]}}, mulcsd_temp_5});

  assign mulcsd_temp_6 = 
        $signed({input_pipeline_phase0[6], 9'b000000000}) +
        $signed({input_pipeline_phase0[6], 6'b000000}) +
        $signed({input_pipeline_phase0[6], 2'b00}) -
        input_pipeline_phase0[6];
  assign product_phase0_8 = $signed({{6{mulcsd_temp_6[31]}}, mulcsd_temp_6});

  assign mulcsd_temp_7 = 
        $signed({input_pipeline_phase0[7], 14'b00000000000000}) -
        $signed({input_pipeline_phase0[7], 10'b0000000000}) +
        $signed({input_pipeline_phase0[7], 9'b000000000}) -
        $signed({input_pipeline_phase0[7], 7'b0000000}) +
        $signed({input_pipeline_phase0[7], 5'b00000});
  assign product_phase0_9 = $signed({{1{mulcsd_temp_7[36]}}, mulcsd_temp_7});

  assign mulcsd_temp_8 = 
        $signed({input_pipeline_phase0[8], 9'b000000000}) +
        $signed({input_pipeline_phase0[8], 6'b000000}) +
        $signed({input_pipeline_phase0[8], 2'b00}) -
        input_pipeline_phase0[8];
  assign product_phase0_10 = $signed({{6{mulcsd_temp_8[31]}}, mulcsd_temp_8});

  assign mulcsd_temp_9 = - (
        $signed({input_pipeline_phase0[9], 9'b000000000}) -
        $signed({input_pipeline_phase0[9], 4'b0000}) +
        $signed({input_pipeline_phase0[9], 2'b00}) -
        input_pipeline_phase0[9]);
  assign product_phase0_11 = $signed({{6{mulcsd_temp_9[31]}}, mulcsd_temp_9});

  assign mulcsd_temp_10 = 
        $signed({input_pipeline_phase0[10], 9'b000000000}) -
        $signed({input_pipeline_phase0[10], 7'b0000000}) +
        $signed({input_pipeline_phase0[10], 2'b00}) -
        input_pipeline_phase0[10];
  assign product_phase0_12 = $signed({{6{mulcsd_temp_10[31]}}, mulcsd_temp_10});

  assign mulcsd_temp_11 = - (
        $signed({input_pipeline_phase0[11], 8'b00000000}) +
        $signed({input_pipeline_phase0[11], 3'b000}) +
        $signed({input_pipeline_phase0[11], 1'b0}));
  assign product_phase0_13 = $signed({{7{mulcsd_temp_11[30]}}, mulcsd_temp_11});

  assign mulcsd_temp_12 = 
        $signed({input_pipeline_phase0[12], 7'b0000000}) +
        $signed({input_pipeline_phase0[12], 5'b00000});
  assign product_phase0_14 = $signed({{8{mulcsd_temp_12[29]}}, mulcsd_temp_12});

  assign mulcsd_temp_13 = - (
        $signed({input_pipeline_phase0[13], 6'b000000}) +
        $signed({input_pipeline_phase0[13], 4'b0000}));
  assign product_phase0_15 = $signed({{9{mulcsd_temp_13[28]}}, mulcsd_temp_13});

  assign product_phase0_16 = $signed({input_pipeline_phase0[14][21:0], 5'b00000});

  assign mulcsd_temp_14 = - (
        $signed({input_pipeline_phase0[15], 2'b00}) +
        input_pipeline_phase0[15]);
  assign product_phase0_17 = $signed({{13{mulcsd_temp_14[24]}}, mulcsd_temp_14});

  assign mulpwr2_temp = (input_pipeline_phase1[0]==22'b1000000000000000000000) ? $signed({1'b0, input_pipeline_phase1[0]}) : -input_pipeline_phase1[0];

  assign product_phase1_1 = $signed({mulpwr2_temp[22:0], 1'b0});

  assign mulcsd_temp_15 = 
        $signed({input_pipeline_phase1[1], 5'b00000}) +
        $signed({input_pipeline_phase1[1], 2'b00});
  assign product_phase1_2 = $signed({{10{mulcsd_temp_15[27]}}, mulcsd_temp_15});

  assign mulcsd_temp_16 = - (
        $signed({input_pipeline_phase1[2], 7'b0000000}) -
        $signed({input_pipeline_phase1[2], 2'b00}));
  assign product_phase1_3 = $signed({{8{mulcsd_temp_16[29]}}, mulcsd_temp_16});

  assign mulcsd_temp_17 = 
        $signed({input_pipeline_phase1[3], 8'b00000000}) +
        $signed({input_pipeline_phase1[3], 6'b000000}) +
        input_pipeline_phase1[3];
  assign product_phase1_4 = $signed({{7{mulcsd_temp_17[30]}}, mulcsd_temp_17});

  assign mulcsd_temp_18 = - (
        $signed({input_pipeline_phase1[4], 9'b000000000}) +
        $signed({input_pipeline_phase1[4], 8'b00000000}) -
        $signed({input_pipeline_phase1[4], 6'b000000}) +
        $signed({input_pipeline_phase1[4], 2'b00}));
  assign product_phase1_5 = $signed({{6{mulcsd_temp_18[31]}}, mulcsd_temp_18});

  assign mulcsd_temp_19 = 
        $signed({input_pipeline_phase1[5], 10'b0000000000}) +
        $signed({input_pipeline_phase1[5], 9'b000000000}) -
        $signed({input_pipeline_phase1[5], 7'b0000000}) +
        $signed({input_pipeline_phase1[5], 5'b00000}) +
        input_pipeline_phase1[5];
  assign product_phase1_6 = $signed({{5{mulcsd_temp_19[32]}}, mulcsd_temp_19});

  assign mulcsd_temp_20 = - (
        $signed({input_pipeline_phase1[6], 11'b00000000000}) +
        $signed({input_pipeline_phase1[6], 10'b0000000000}) -
        $signed({input_pipeline_phase1[6], 5'b00000}) +
        $signed({input_pipeline_phase1[6], 3'b000}) +
        $signed({input_pipeline_phase1[6], 2'b00}) -
        input_pipeline_phase1[6]);
  assign product_phase1_7 = $signed({{4{mulcsd_temp_20[33]}}, mulcsd_temp_20});

  assign mulcsd_temp_21 = 
        $signed({input_pipeline_phase1[7], 13'b0000000000000}) +
        $signed({input_pipeline_phase1[7], 11'b00000000000}) +
        $signed({input_pipeline_phase1[7], 5'b00000}) +
        $signed({input_pipeline_phase1[7], 3'b000}) +
        input_pipeline_phase1[7];
  assign product_phase1_8 = $signed({{2{mulcsd_temp_21[35]}}, mulcsd_temp_21});

  assign mulcsd_temp_22 = 
        $signed({input_pipeline_phase1[8], 13'b0000000000000}) +
        $signed({input_pipeline_phase1[8], 11'b00000000000}) +
        $signed({input_pipeline_phase1[8], 5'b00000}) +
        $signed({input_pipeline_phase1[8], 3'b000}) +
        input_pipeline_phase1[8];
  assign product_phase1_9 = $signed({{2{mulcsd_temp_22[35]}}, mulcsd_temp_22});

  assign mulcsd_temp_23 = - (
        $signed({input_pipeline_phase1[9], 11'b00000000000}) +
        $signed({input_pipeline_phase1[9], 10'b0000000000}) -
        $signed({input_pipeline_phase1[9], 5'b00000}) +
        $signed({input_pipeline_phase1[9], 3'b000}) +
        $signed({input_pipeline_phase1[9], 2'b00}) -
        input_pipeline_phase1[9]);
  assign product_phase1_10 = $signed({{4{mulcsd_temp_23[33]}}, mulcsd_temp_23});

  assign mulcsd_temp_24 = 
        $signed({input_pipeline_phase1[10], 10'b0000000000}) +
        $signed({input_pipeline_phase1[10], 9'b000000000}) -
        $signed({input_pipeline_phase1[10], 7'b0000000}) +
        $signed({input_pipeline_phase1[10], 5'b00000}) +
        input_pipeline_phase1[10];
  assign product_phase1_11 = $signed({{5{mulcsd_temp_24[32]}}, mulcsd_temp_24});

  assign mulcsd_temp_25 = - (
        $signed({input_pipeline_phase1[11], 9'b000000000}) +
        $signed({input_pipeline_phase1[11], 8'b00000000}) -
        $signed({input_pipeline_phase1[11], 6'b000000}) +
        $signed({input_pipeline_phase1[11], 2'b00}));
  assign product_phase1_12 = $signed({{6{mulcsd_temp_25[31]}}, mulcsd_temp_25});

  assign mulcsd_temp_26 = 
        $signed({input_pipeline_phase1[12], 8'b00000000}) +
        $signed({input_pipeline_phase1[12], 6'b000000}) +
        input_pipeline_phase1[12];
  assign product_phase1_13 = $signed({{7{mulcsd_temp_26[30]}}, mulcsd_temp_26});

  assign mulcsd_temp_27 = - (
        $signed({input_pipeline_phase1[13], 7'b0000000}) -
        $signed({input_pipeline_phase1[13], 2'b00}));
  assign product_phase1_14 = $signed({{8{mulcsd_temp_27[29]}}, mulcsd_temp_27});

  assign mulcsd_temp_28 = 
        $signed({input_pipeline_phase1[14], 5'b00000}) +
        $signed({input_pipeline_phase1[14], 2'b00});
  assign product_phase1_15 = $signed({{10{mulcsd_temp_28[27]}}, mulcsd_temp_28});

  assign mulpwr2_temp_1 = (input_pipeline_phase1[15]==22'b1000000000000000000000) ? $signed({1'b0, input_pipeline_phase1[15]}) : -input_pipeline_phase1[15];

  assign product_phase1_16 = $signed({mulpwr2_temp_1[22:0], 1'b0});

  assign quantized_sum = $signed({{16{product_phase1_1[37]}}, product_phase1_1});

  assign add_signext = quantized_sum;
  assign add_signext_1 = $signed({{16{product_phase1_2[37]}}, product_phase1_2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[53:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{16{product_phase1_3[37]}}, product_phase1_3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[53:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{16{product_phase1_4[37]}}, product_phase1_4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[53:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{16{product_phase1_5[37]}}, product_phase1_5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[53:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{16{product_phase1_6[37]}}, product_phase1_6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[53:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{16{product_phase1_7[37]}}, product_phase1_7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[53:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{16{product_phase1_8[37]}}, product_phase1_8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[53:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{16{product_phase1_9[37]}}, product_phase1_9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[53:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{16{product_phase1_10[37]}}, product_phase1_10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[53:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{16{product_phase1_11[37]}}, product_phase1_11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[53:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{16{product_phase1_12[37]}}, product_phase1_12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[53:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{16{product_phase1_13[37]}}, product_phase1_13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[53:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{16{product_phase1_14[37]}}, product_phase1_14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[53:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{16{product_phase1_15[37]}}, product_phase1_15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[53:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{16{product_phase1_16[37]}}, product_phase1_16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[53:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{16{product_phase0_1[37]}}, product_phase0_1});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[53:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{16{product_phase0_2[37]}}, product_phase0_2});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[53:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{16{product_phase0_3[37]}}, product_phase0_3});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[53:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{16{product_phase0_4[37]}}, product_phase0_4});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[53:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{16{product_phase0_5[37]}}, product_phase0_5});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[53:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{16{product_phase0_6[37]}}, product_phase0_6});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[53:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{16{product_phase0_7[37]}}, product_phase0_7});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[53:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{16{product_phase0_8[37]}}, product_phase0_8});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[53:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{16{product_phase0_9[37]}}, product_phase0_9});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[53:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{16{product_phase0_10[37]}}, product_phase0_10});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[53:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{16{product_phase0_11[37]}}, product_phase0_11});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[53:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{16{product_phase0_12[37]}}, product_phase0_12});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[53:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{16{product_phase0_13[37]}}, product_phase0_13});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[53:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{16{product_phase0_14[37]}}, product_phase0_14});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[53:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{16{product_phase0_15[37]}}, product_phase0_15});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[53:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{16{product_phase0_16[37]}}, product_phase0_16});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[53:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{16{product_phase0_17[37]}}, product_phase0_17});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[53:0];

  assign output_typeconvert = sum32[36:15];

  always @ (posedge clk or posedge reset)
    begin: output_register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // output_register_process

  // Assignment Statements
  assign ce_out = ce_out_reg;
  assign filter_out = output_register;
endmodule  // Stage5_FIR
